name: Node CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x, 20.x, 22.x]

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }} # Dynamic name based on version
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }} # Matrix version use ho rahi hai
        cache: 'npm'

    - name: Install deps
      run: npm ci

    - name: Run tests

      env:
        API_KEY: ${{ secrets.API_KEY }}
      run: npm test
